### ISSUE TITLE
url投稿

### ISSUE THREAD

**Issue by Junya-kobayashi** [Junya-kobayashi/musicApp#2]
firebaseを用いてデータベースに追加してデータベースから出力する作業

**Comment by Junya-kobayashi** [comment]
urlをfirebaseに追加

**Comment by Junya-kobayashi** [comment]
urlをfirebaseから出力する

**Comment by Junya-kobayashi** [comment]
記事を出力

**Comment by Junya-kobayashi** [comment]
tableviewを出力

**Comment by Junya-kobayashi** [comment]
returnを押したらキーボードを閉じる

**Comment by Junya-kobayashi** [comment]
textfieldの設定

**Comment by Junya-kobayashi** [comment]
2017-09-26 23:53:39.752175+0900 musicApp[16217:2236436] [Firebase/Database][I-RDB038012] setValue: or removeValue: at /user/01 failed: permission_denied

firebaseにこんなものが投稿されている...

**Comment by s11y** [comment]
これやと思う

firebase databaseのruleの設定
https://stackoverflow.com/a/43295908/5941232

**Comment by Junya-kobayashi** [comment]
firebaseに入力したurlをtable viewで一つ一つ出力する -- doing

**Comment by Junya-kobayashi** [comment]
navigation barにあるpostからtextViewの場面にとび、そこからurlを書いた上でpostを押すとfirebaseにurlが格納され、それをtableviewに出力する

**Comment by Junya-kobayashi** [comment]
reason: '-[UITableViewController loadView] loaded the "EX8-dH-Aa6-vi…
…ew-zyo-s1-h0s" nib but didn't get a UITableView.'

が出て現在のviewを実行できない
